# Generated by Django 2.1 on 2018-08-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180821_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImg',
            field=models.ImageField(null=True, upload_to='user'),
        ),
    ]
