# Generated by Django 2.1 on 2018-08-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='ImgFile',
            field=models.ImageField(blank=True, upload_to='post'),
        ),
    ]
