# Generated by Django 2.1 on 2018-08-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180822_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userid',
            new_name='writer',
        ),
    ]
