# Generated by Django 2.1 on 2018-08-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20180822_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='videlink',
            new_name='videolink',
        ),
    ]
